import 'dart:ui';

import 'package:plotline_task/src/services/tooltip/tooltip_position.dart';

import '../../models/tooltip_model.dart';

List<TooltipProperties> defaultProperties = [
  TooltipProperties(
      isHidden: true,
      targetElement: 'Button 1',
      tooltipText: 'Rishabh',
      textSize: 20,
      padding: 2,
      textColor: const Color.fromRGBO(18, 18, 18, 1),
      backgroundColor: const Color.fromRGBO(255, 0, 0, 1),
      cornerRadius: 10,
      tooltipWidth: 100,
      arrowWidth: 20,
      arrowHeight: 10,
      tooltipPosition: TooltipPosition.auto,
      aspectRatio: 1),
  TooltipProperties(
      isHidden: true,
      targetElement: 'Button 2',
      tooltipText: 'Rishabh',
      textSize: 20,
      padding: 2,
      textColor: const Color.fromRGBO(18, 18, 18, 1),
      backgroundColor: const Color.fromRGBO(255, 0, 0, 1),
      cornerRadius: 10,
      tooltipWidth: 100,
      arrowWidth: 20,
      arrowHeight: 10,
      tooltipPosition: TooltipPosition.auto,
      aspectRatio: 1),
  TooltipProperties(
      isHidden: true,
      targetElement: 'Button 3',
      tooltipText: 'Rishabh',
      textSize: 20,
      padding: 2,
      textColor: const Color.fromRGBO(18, 18, 18, 1),
      backgroundColor: const Color.fromRGBO(255, 0, 0, 1),
      cornerRadius: 10,
      tooltipWidth: 100,
      arrowWidth: 20,
      arrowHeight: 10,
      tooltipPosition: TooltipPosition.auto,
      aspectRatio: 1),
  TooltipProperties(
      isHidden: true,
      targetElement: 'Button 4',
      tooltipText: 'Rishabh',
      textSize: 20,
      padding: 2,
      textColor: const Color.fromRGBO(18, 18, 18, 1),
      backgroundColor: const Color.fromRGBO(255, 0, 0, 1),
      cornerRadius: 10,
      tooltipWidth: 100,
      arrowWidth: 20,
      arrowHeight: 10,
      tooltipPosition: TooltipPosition.auto,
      aspectRatio: 1),
  TooltipProperties(
      isHidden: true,
      targetElement: 'Button 5',
      tooltipText: 'Rishabh',
      textSize: 20,
      padding: 2,
      textColor: const Color.fromRGBO(18, 18, 18, 1),
      backgroundColor: const Color.fromRGBO(255, 0, 0, 1),
      cornerRadius: 10,
      tooltipWidth: 100,
      arrowWidth: 20,
      arrowHeight: 10,
      tooltipPosition: TooltipPosition.auto,
      aspectRatio: 1)
];
