import 'package:flutter/material.dart';
import 'package:plotline_task/src/services/tooltip/tooltipPosition.dart';


import '../../models/tooltip_model.dart';

List<TooltipProperties> defaultProperties = [
  TooltipProperties(
      isHidden: true,
      targetElement: 'Button 1',
      tooltipText: 'Rishabh',
      textSize: 25,
      padding: 2,
      textColor: Colors.white,
      backgroundColor: Colors.black,
      cornerRadius: 10,
      tooltipWidth: 100,
      arrowWidth: 20,
      arrowHeight: 10,
      tooltipPosition: TooltipPosition.auto,
      aspectRatio: 1),
  TooltipProperties(
      isHidden: true,
      targetElement: 'Button 2',
      tooltipText: 'Rishabh',
      textSize: 25,
      padding: 2,
      textColor: Colors.white,
      backgroundColor: Colors.black,
      cornerRadius: 10,
      tooltipWidth: 100,
      arrowWidth: 20,
      arrowHeight: 10,
      tooltipPosition: TooltipPosition.auto,
      aspectRatio: 1),
  TooltipProperties(
      isHidden: true,
      targetElement: 'Button 3',
      tooltipText: 'Rishabh',
      textSize: 25,
      padding: 2,
      textColor: Colors.white,
      backgroundColor: Colors.black,
      cornerRadius: 10,
      tooltipWidth: 100,
      arrowWidth: 20,
      arrowHeight: 10,
      tooltipPosition: TooltipPosition.auto,
      aspectRatio: 1),
  TooltipProperties(
      isHidden: true,
      targetElement: 'Button 4',
      tooltipText: 'Rishabh',
      textSize: 25,
      padding: 2,
      textColor: Colors.white,
      backgroundColor: Colors.black,
      cornerRadius: 10,
      tooltipWidth: 100,
      arrowWidth: 20,
      arrowHeight: 10,
      tooltipPosition: TooltipPosition.auto,
      aspectRatio: 1),
  TooltipProperties(
      isHidden: true,
      targetElement: 'Button 5',
      tooltipText: 'Rishabh',
      textSize: 25,
      padding: 2,
      textColor: Colors.white,
      backgroundColor: Colors.black,
      cornerRadius: 10,
      tooltipWidth: 100,
      arrowWidth: 20,
      arrowHeight: 10,
      tooltipPosition: TooltipPosition.auto,
      aspectRatio: 1)
];
